# ==========================================================================
# CRE PROJECT SETTINGS — Lead Engine CRE
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Each target defines cre-cli, account, and rpcs groups.
#
# Workflows:
#   - EvaluateBuyerRulesAndMatch: Buyer rule evaluation + matching
#   - DecryptForWinner: Winner-only PII decryption (encryptOutput: true)
#
# Reference: cre-templates/conf-http-demo/project.yaml

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
